import { getTranslations, setRequestLocale } from "next-intl/server";
import { Link } from "@/i18n/navigation";
import { routing } from "@/i18n/routing";
import { FOCUS_RING, SessionPanel } from "./session-panel";

// Style-consistent placeholder for the full-screen photo of A11; decision #26
// swaps this one file for the final art. Generated by us with sharp, not
// third-party art: no attribution and no licence obligation ride on it, which
// is exactly what #26 has to answer for the real photo. Pre-optimized WebP
// served straight from /public — next/image would only re-proxy an
// already-final asset, as the profile page notes.
const PHOTO_PLACEHOLDER_PATH = "/landing-placeholder.webp";

export default async function HomePage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);
  const t = await getTranslations("HomePage");
  const tSwitcher = await getTranslations("LanguageSwitcher");

  return (
    // isolate, not just relative: without a stacking context of its own the
    // two -z-10 layers below paint in the ROOT one, and any background added
    // later on main or on a wrapper would silently swallow the photo.
    <main className="relative isolate flex min-h-screen flex-col items-center justify-center px-4 py-12">
      {/* Decorative: the card below carries every piece of information, so
          the image needs no description. */}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={PHOTO_PLACEHOLDER_PATH}
        alt=""
        aria-hidden="true"
        width={1920}
        height={1080}
        fetchPriority="high"
        className="absolute inset-0 -z-10 h-full w-full object-cover"
      />
      {/* Scrim: keeps the photo from fighting the card whatever #26 puts
          underneath. Lighter than the card on purpose — the photo should still
          read as a photo around it. */}
      <div
        aria-hidden="true"
        className="absolute inset-0 -z-10 bg-gray-950/50"
      />

      {/* Opaque, not translucent: a see-through card over an unknown photo has
          no measurable text contrast (axe reports it as untestable, #20 runs
          axe here) and its border disappears into the scrim — §1 asks for a
          card with a thin border, so it has to look like one.

          `relative` is what makes that opacity count. Inside a positioned,
          isolated parent axe cannot resolve the background behind a static
          child, so every string here came back "could not be determined" and
          the #20 contrast check passed by measuring nothing: 0 passes and 7
          undecided on 03.09.2026. Positioning the card turns the same seven
          into passes. It changes no pixel — z-index stays auto, so the paint
          order against the two -z-10 layers above is exactly as it was. */}
      <div className="relative flex w-full max-w-md flex-col items-center gap-4 rounded-lg border border-white/20 bg-gray-950 p-8 text-center">
        <h1 className="text-3xl font-semibold tracking-tight text-white">
          {t("brand")}
        </h1>
        <p className="text-gray-200">{t("tagline")}</p>
        <p className="text-sm text-gray-300">{t("lead")}</p>
        <SessionPanel />
        <nav aria-label={tSwitcher("label")} className="flex gap-3 text-sm">
          {routing.locales.map((l) => (
            <Link
              key={l}
              href="/"
              locale={l}
              lang={l}
              hrefLang={l}
              // The name of each language is written in that language, so it
              // needs its own lang for a screen reader to pronounce it (WCAG
              // 3.1.2); aria-current says which page the visitor is on.
              aria-current={l === locale ? "true" : undefined}
              className={`py-1 ${FOCUS_RING} ${
                l === locale
                  ? "font-semibold text-white underline"
                  : "text-gray-300 hover:underline"
              }`}
            >
              {tSwitcher(l)}
            </Link>
          ))}
        </nav>
      </div>
    </main>
  );
}
